[package]
name = "basic-window"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
wgpu = "0.19.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
 